/**
 * Template medicine product masters for chemists / pharmacies.
 * Not stock and not shared serials — each business gets its own product rows.
 * Owner then receives opening stock / GRN only for lines they actually hold.
 */

export type PharmacyStarterProduct = {
  code: string;
  name: string;
  genericName: string;
  productBrand?: string | null;
  sku: string;
  barcode?: string | null;
  categoryName: string;
  dosageFormCode: string;
  drugCategoryCode: string;
  strengthLabel: string;
  prescriptionTypeCode: "OTC" | "POM" | "P";
  stockUnitCode: string;
  salesUnitCode: string;
  purchaseUnitCode: string;
  stripFactor?: number | null;
  boxFactor?: number | null;
  packSize?: string | null;
  description?: string | null;
  minimumStock?: number;
  reorderLevel?: number;
  suggestedCost?: number | null;
  suggestedSell?: number | null;
};

export const DEFAULT_PHARMACY_STARTER_PRODUCTS: PharmacyStarterProduct[] = [
  {
    code: "PARA-500-TAB",
    name: "Paracetamol 500 mg Tablets",
    genericName: "Paracetamol",
    productBrand: "Generic",
    sku: "PARA-500-TAB",
    categoryName: "Pain & Fever",
    dosageFormCode: "TAB",
    drugCategoryCode: "ANALGESIC",
    strengthLabel: "500 mg",
    prescriptionTypeCode: "OTC",
    stockUnitCode: "TAB",
    salesUnitCode: "TAB",
    purchaseUnitCode: "BOX",
    stripFactor: 10,
    boxFactor: 100,
    packSize: "10×10",
    minimumStock: 200,
    reorderLevel: 500,
    suggestedCost: 1.5,
    suggestedSell: 3,
  },
  {
    code: "IBU-400-TAB",
    name: "Ibuprofen 400 mg Tablets",
    genericName: "Ibuprofen",
    sku: "IBU-400-TAB",
    categoryName: "Pain & Fever",
    dosageFormCode: "TAB",
    drugCategoryCode: "ANTIINFLAMMATORY",
    strengthLabel: "400 mg",
    prescriptionTypeCode: "OTC",
    stockUnitCode: "TAB",
    salesUnitCode: "TAB",
    purchaseUnitCode: "BOX",
    stripFactor: 10,
    boxFactor: 100,
    packSize: "10×10",
    minimumStock: 100,
    reorderLevel: 300,
    suggestedCost: 3,
    suggestedSell: 8,
  },
  {
    code: "AMOX-500-CAP",
    name: "Amoxicillin 500 mg Capsules",
    genericName: "Amoxicillin",
    sku: "AMOX-500-CAP",
    categoryName: "Antibiotics",
    dosageFormCode: "CAP",
    drugCategoryCode: "ANTIBIOTIC",
    strengthLabel: "500 mg",
    prescriptionTypeCode: "POM",
    stockUnitCode: "CAP",
    salesUnitCode: "CAP",
    purchaseUnitCode: "BOX",
    stripFactor: 10,
    boxFactor: 100,
    packSize: "10×10",
    minimumStock: 100,
    reorderLevel: 250,
    suggestedCost: 5,
    suggestedSell: 12,
  },
  {
    code: "AMOX-SUS-250",
    name: "Amoxicillin 250 mg/5 mL Suspension",
    genericName: "Amoxicillin",
    sku: "AMOX-SUS-250",
    categoryName: "Antibiotics",
    dosageFormCode: "SUS",
    drugCategoryCode: "ANTIBIOTIC",
    strengthLabel: "250 mg/5 mL",
    prescriptionTypeCode: "POM",
    stockUnitCode: "BOT",
    salesUnitCode: "BOT",
    purchaseUnitCode: "BOX",
    packSize: "100 mL",
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 80,
    suggestedSell: 150,
  },
  {
    code: "AZI-500-TAB",
    name: "Azithromycin 500 mg Tablets",
    genericName: "Azithromycin",
    sku: "AZI-500-TAB",
    categoryName: "Antibiotics",
    dosageFormCode: "TAB",
    drugCategoryCode: "ANTIBIOTIC",
    strengthLabel: "500 mg",
    prescriptionTypeCode: "POM",
    stockUnitCode: "TAB",
    salesUnitCode: "TAB",
    purchaseUnitCode: "BOX",
    stripFactor: 3,
    boxFactor: 30,
    packSize: "3's",
    minimumStock: 30,
    reorderLevel: 80,
    suggestedCost: 40,
    suggestedSell: 75,
  },
  {
    code: "CIP-500-TAB",
    name: "Ciprofloxacin 500 mg Tablets",
    genericName: "Ciprofloxacin",
    sku: "CIP-500-TAB",
    categoryName: "Antibiotics",
    dosageFormCode: "TAB",
    drugCategoryCode: "ANTIBIOTIC",
    strengthLabel: "500 mg",
    prescriptionTypeCode: "POM",
    stockUnitCode: "TAB",
    salesUnitCode: "TAB",
    purchaseUnitCode: "BOX",
    stripFactor: 10,
    boxFactor: 100,
    minimumStock: 50,
    reorderLevel: 150,
    suggestedCost: 8,
    suggestedSell: 18,
  },
  {
    code: "AUG-625-TAB",
    name: "Amoxicillin/Clavulanate 625 mg Tablets",
    genericName: "Amoxicillin + Clavulanic acid",
    productBrand: "Augmentin-type",
    sku: "AUG-625-TAB",
    categoryName: "Antibiotics",
    dosageFormCode: "TAB",
    drugCategoryCode: "ANTIBIOTIC",
    strengthLabel: "625 mg",
    prescriptionTypeCode: "POM",
    stockUnitCode: "TAB",
    salesUnitCode: "TAB",
    purchaseUnitCode: "BOX",
    stripFactor: 10,
    boxFactor: 100,
    minimumStock: 40,
    reorderLevel: 100,
    suggestedCost: 25,
    suggestedSell: 50,
  },
  {
    code: "MET-500-TAB",
    name: "Metronidazole 500 mg Tablets",
    genericName: "Metronidazole",
    sku: "MET-500-TAB",
    categoryName: "Antibiotics",
    dosageFormCode: "TAB",
    drugCategoryCode: "ANTIBIOTIC",
    strengthLabel: "500 mg",
    prescriptionTypeCode: "POM",
    stockUnitCode: "TAB",
    salesUnitCode: "TAB",
    purchaseUnitCode: "BOX",
    stripFactor: 10,
    boxFactor: 100,
    minimumStock: 80,
    reorderLevel: 200,
    suggestedCost: 2,
    suggestedSell: 5,
  },
  {
    code: "CET-10-TAB",
    name: "Cetirizine 10 mg Tablets",
    genericName: "Cetirizine",
    sku: "CET-10-TAB",
    categoryName: "Allergy",
    dosageFormCode: "TAB",
    drugCategoryCode: "ANTIHISTAMINE",
    strengthLabel: "10 mg",
    prescriptionTypeCode: "OTC",
    stockUnitCode: "TAB",
    salesUnitCode: "TAB",
    purchaseUnitCode: "BOX",
    stripFactor: 10,
    boxFactor: 100,
    minimumStock: 100,
    reorderLevel: 250,
    suggestedCost: 2,
    suggestedSell: 5,
  },
  {
    code: "OME-20-CAP",
    name: "Omeprazole 20 mg Capsules",
    genericName: "Omeprazole",
    sku: "OME-20-CAP",
    categoryName: "GIT",
    dosageFormCode: "CAP",
    drugCategoryCode: "ANTIULCER",
    strengthLabel: "20 mg",
    prescriptionTypeCode: "OTC",
    stockUnitCode: "CAP",
    salesUnitCode: "CAP",
    purchaseUnitCode: "BOX",
    stripFactor: 14,
    boxFactor: 28,
    minimumStock: 50,
    reorderLevel: 120,
    suggestedCost: 5,
    suggestedSell: 12,
  },
  {
    code: "ORS-SACH",
    name: "ORS Sachets",
    genericName: "Oral rehydration salts",
    sku: "ORS-SACH",
    categoryName: "GIT",
    dosageFormCode: "POW",
    drugCategoryCode: "ELECTROLYTE",
    strengthLabel: "1 g",
    prescriptionTypeCode: "OTC",
    stockUnitCode: "SACH",
    salesUnitCode: "SACH",
    purchaseUnitCode: "BOX",
    boxFactor: 50,
    packSize: "20.5 g sachet",
    minimumStock: 40,
    reorderLevel: 100,
    suggestedCost: 10,
    suggestedSell: 20,
  },
  {
    code: "ALB-400-TAB",
    name: "Albendazole 400 mg Tablets",
    genericName: "Albendazole",
    sku: "ALB-400-TAB",
    categoryName: "Antiparasitic",
    dosageFormCode: "TAB",
    drugCategoryCode: "ANTHELMINTIC",
    strengthLabel: "400 mg",
    prescriptionTypeCode: "OTC",
    stockUnitCode: "TAB",
    salesUnitCode: "TAB",
    purchaseUnitCode: "BOX",
    stripFactor: 1,
    boxFactor: 100,
    packSize: "Single dose",
    minimumStock: 30,
    reorderLevel: 80,
    suggestedCost: 15,
    suggestedSell: 35,
  },
  {
    code: "LOS-50-TAB",
    name: "Losartan 50 mg Tablets",
    genericName: "Losartan",
    sku: "LOS-50-TAB",
    categoryName: "Cardiovascular",
    dosageFormCode: "TAB",
    drugCategoryCode: "ANTIHYPERTENSIVE",
    strengthLabel: "50 mg",
    prescriptionTypeCode: "POM",
    stockUnitCode: "TAB",
    salesUnitCode: "TAB",
    purchaseUnitCode: "BOX",
    stripFactor: 10,
    boxFactor: 30,
    minimumStock: 60,
    reorderLevel: 150,
    suggestedCost: 4,
    suggestedSell: 10,
  },
  {
    code: "AML-5-TAB",
    name: "Amlodipine 5 mg Tablets",
    genericName: "Amlodipine",
    sku: "AML-5-TAB",
    categoryName: "Cardiovascular",
    dosageFormCode: "TAB",
    drugCategoryCode: "ANTIHYPERTENSIVE",
    strengthLabel: "5 mg",
    prescriptionTypeCode: "POM",
    stockUnitCode: "TAB",
    salesUnitCode: "TAB",
    purchaseUnitCode: "BOX",
    stripFactor: 10,
    boxFactor: 30,
    minimumStock: 60,
    reorderLevel: 150,
    suggestedCost: 2.5,
    suggestedSell: 7,
  },
  {
    code: "METF-500-TAB",
    name: "Metformin 500 mg Tablets",
    genericName: "Metformin",
    sku: "METF-500-TAB",
    categoryName: "Diabetes",
    dosageFormCode: "TAB",
    drugCategoryCode: "ANTIDIABETIC",
    strengthLabel: "500 mg",
    prescriptionTypeCode: "POM",
    stockUnitCode: "TAB",
    salesUnitCode: "TAB",
    purchaseUnitCode: "BOX",
    stripFactor: 10,
    boxFactor: 100,
    minimumStock: 100,
    reorderLevel: 300,
    suggestedCost: 1.5,
    suggestedSell: 4,
  },
  {
    code: "SAL-INH-100",
    name: "Salbutamol Inhaler 100 mcg",
    genericName: "Salbutamol",
    productBrand: "Ventolin-type",
    sku: "SAL-INH-100",
    categoryName: "Respiratory",
    dosageFormCode: "INH",
    drugCategoryCode: "BRONCHODILATOR",
    strengthLabel: "100 mcg",
    prescriptionTypeCode: "POM",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "BOX",
    packSize: "200 doses",
    minimumStock: 5,
    reorderLevel: 15,
    suggestedCost: 180,
    suggestedSell: 320,
  },
  {
    code: "COUGH-SYP-100",
    name: "Cough Syrup 100 mL",
    genericName: "Cough mixture",
    sku: "COUGH-SYP-100",
    categoryName: "Respiratory",
    dosageFormCode: "SYP",
    drugCategoryCode: "EXPECTORANT",
    strengthLabel: "100 mg/5 mL",
    prescriptionTypeCode: "OTC",
    stockUnitCode: "BOT",
    salesUnitCode: "BOT",
    purchaseUnitCode: "BOX",
    packSize: "100 mL",
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 60,
    suggestedSell: 120,
  },
  {
    code: "DIC-GEL-30",
    name: "Diclofenac Gel 30 g",
    genericName: "Diclofenac",
    sku: "DIC-GEL-30",
    categoryName: "Pain & Fever",
    dosageFormCode: "GEL",
    drugCategoryCode: "ANTIINFLAMMATORY",
    strengthLabel: "1%",
    prescriptionTypeCode: "OTC",
    stockUnitCode: "TUBE",
    salesUnitCode: "TUBE",
    purchaseUnitCode: "BOX",
    packSize: "30 g",
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 70,
    suggestedSell: 140,
  },
  {
    code: "HC-CRM-15",
    name: "Hydrocortisone Cream 15 g",
    genericName: "Hydrocortisone",
    sku: "HC-CRM-15",
    categoryName: "Dermatology",
    dosageFormCode: "CRM",
    drugCategoryCode: "CORTICOSTEROID",
    strengthLabel: "1%",
    prescriptionTypeCode: "OTC",
    stockUnitCode: "TUBE",
    salesUnitCode: "TUBE",
    purchaseUnitCode: "BOX",
    packSize: "15 g",
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 55,
    suggestedSell: 110,
  },
  {
    code: "EYE-TEAR-10",
    name: "Artificial Tears Eye Drops 10 mL",
    genericName: "Carboxymethylcellulose",
    sku: "EYE-TEAR-10",
    categoryName: "Eye care",
    dosageFormCode: "DRP",
    drugCategoryCode: "OPHTHALMIC",
    strengthLabel: "0.5%",
    prescriptionTypeCode: "OTC",
    stockUnitCode: "BOT",
    salesUnitCode: "BOT",
    purchaseUnitCode: "BOX",
    packSize: "10 mL",
    minimumStock: 8,
    reorderLevel: 20,
    suggestedCost: 95,
    suggestedSell: 180,
  },
  {
    code: "MULTI-VIT-TAB",
    name: "Multivitamin Tablets",
    genericName: "Multivitamins",
    sku: "MULTI-VIT-TAB",
    categoryName: "Supplements",
    dosageFormCode: "TAB",
    drugCategoryCode: "VITAMIN",
    strengthLabel: "1 g",
    prescriptionTypeCode: "OTC",
    stockUnitCode: "TAB",
    salesUnitCode: "TAB",
    purchaseUnitCode: "BOX",
    stripFactor: 10,
    boxFactor: 30,
    minimumStock: 100,
    reorderLevel: 250,
    suggestedCost: 2,
    suggestedSell: 5,
  },
  {
    code: "INS-GLAR",
    name: "Insulin Glargine 100 IU/mL",
    genericName: "Insulin glargine",
    sku: "INS-GLAR",
    categoryName: "Diabetes",
    dosageFormCode: "INJ",
    drugCategoryCode: "ANTIDIABETIC",
    strengthLabel: "100 IU/mL",
    prescriptionTypeCode: "POM",
    stockUnitCode: "VIAL",
    salesUnitCode: "VIAL",
    purchaseUnitCode: "BOX",
    packSize: "3 mL",
    minimumStock: 3,
    reorderLevel: 10,
    suggestedCost: 1200,
    suggestedSell: 1800,
  },
  {
    code: "GLOVE-M",
    name: "Surgical Gloves Medium (pair)",
    genericName: "Examination gloves",
    sku: "GLOVE-M",
    categoryName: "Consumables",
    dosageFormCode: "PCS",
    drugCategoryCode: "DERMATOLOGICAL",
    strengthLabel: "1 g",
    prescriptionTypeCode: "OTC",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "BOX",
    boxFactor: 100,
    packSize: "Pair",
    description: "Non-medicine consumable",
    minimumStock: 20,
    reorderLevel: 50,
    suggestedCost: 15,
    suggestedSell: 30,
  },
  {
    code: "MASK-50",
    name: "Face Masks Box of 50",
    genericName: "Surgical mask",
    sku: "MASK-50",
    categoryName: "Consumables",
    dosageFormCode: "PCS",
    drugCategoryCode: "DERMATOLOGICAL",
    strengthLabel: "1 g",
    prescriptionTypeCode: "OTC",
    stockUnitCode: "BOX",
    salesUnitCode: "BOX",
    purchaseUnitCode: "BOX",
    packSize: "50 pcs",
    minimumStock: 5,
    reorderLevel: 15,
    suggestedCost: 120,
    suggestedSell: 250,
  },
  {
    code: "SYR-5ML",
    name: "Syringe 5 mL (each)",
    genericName: "Disposable syringe",
    sku: "SYR-5ML",
    categoryName: "Consumables",
    dosageFormCode: "PCS",
    drugCategoryCode: "DERMATOLOGICAL",
    strengthLabel: "1 g",
    prescriptionTypeCode: "OTC",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "BOX",
    boxFactor: 100,
    minimumStock: 30,
    reorderLevel: 100,
    suggestedCost: 5,
    suggestedSell: 12,
  },
];

export function getPharmacyStarterByCodes(codes: string[]): PharmacyStarterProduct[] {
  const set = new Set(codes.map((c) => c.trim().toUpperCase()));
  return DEFAULT_PHARMACY_STARTER_PRODUCTS.filter((p) =>
    set.has(p.code.toUpperCase()),
  );
}
