/**
 * Industry product starter kits (product masters only — no stock).
 * Kits: hardware, agrovet, motorbike, auto
 * Owner selects lines → creates products → receives stock / opening stock.
 */

export type IndustryStarterKitId =
  | "hardware"
  | "agrovet"
  | "motorbike"
  | "auto";

export type IndustryStarterProduct = {
  kit: IndustryStarterKitId;
  code: string;
  name: string;
  sku: string;
  barcode?: string | null;
  categoryName: string;
  stockUnitCode: string;
  salesUnitCode: string;
  purchaseUnitCode: string;
  boxFactor?: number | null;
  serialized?: boolean;
  trackBatch?: boolean;
  trackExpiry?: boolean;
  productBrand?: string | null;
  description?: string | null;
  minimumStock?: number;
  reorderLevel?: number;
  suggestedCost?: number | null;
  suggestedSell?: number | null;
};

export const INDUSTRY_STARTER_KIT_META: Record<
  IndustryStarterKitId,
  { label: string; description: string }
> = {
  hardware: {
    label: "Hardware & building",
    description: "Cement, steel, timber, plumbing, electrical, paint, tools",
  },
  agrovet: {
    label: "Agrovet / farm supplies",
    description: "Fertilizer, seeds, agrochemicals, animal health, feeds, farm tools",
  },
  motorbike: {
    label: "Motorbike & 3-wheeler parts",
    description: "Filters, brakes, chains, oils, body parts + complete units (serialized)",
  },
  auto: {
    label: "Auto / car parts",
    description: "Filters, brakes, oils, suspension, tyres, engine parts",
  },
};

export const DEFAULT_INDUSTRY_STARTER_PRODUCTS: IndustryStarterProduct[] = [
  // ——— Hardware ———

  {
    kit: "hardware",
    code: "HW-CEM-50",
    name: "Portland Cement 50 kg",
    sku: "HW-CEM-50",
    categoryName: "Cement & Concrete",
    stockUnitCode: "BAG",
    salesUnitCode: "BAG",
    purchaseUnitCode: "BAG",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: "50 kg bag",
    minimumStock: 20,
    reorderLevel: 50,
    suggestedCost: 750,
    suggestedSell: 950,
  },
  {
    kit: "hardware",
    code: "HW-SAND-TON",
    name: "Building Sand (ton)",
    sku: "HW-SAND-TON",
    categoryName: "Aggregates",
    stockUnitCode: "TON",
    salesUnitCode: "TON",
    purchaseUnitCode: "TON",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 5,
    reorderLevel: 15,
    suggestedCost: 2500,
    suggestedSell: 3500,
  },
  {
    kit: "hardware",
    code: "HW-BALLAST-TON",
    name: "Ballast (ton)",
    sku: "HW-BALLAST-TON",
    categoryName: "Aggregates",
    stockUnitCode: "TON",
    salesUnitCode: "TON",
    purchaseUnitCode: "TON",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 5,
    reorderLevel: 15,
    suggestedCost: 2800,
    suggestedSell: 3800,
  },
  {
    kit: "hardware",
    code: "HW-BLOCK-6",
    name: "Concrete Block 6 inch",
    sku: "HW-BLOCK-6",
    categoryName: "Masonry",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 200,
    reorderLevel: 500,
    suggestedCost: 45,
    suggestedSell: 70,
  },
  {
    kit: "hardware",
    code: "HW-BLOCK-9",
    name: "Concrete Block 9 inch",
    sku: "HW-BLOCK-9",
    categoryName: "Masonry",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 200,
    reorderLevel: 500,
    suggestedCost: 55,
    suggestedSell: 85,
  },
  {
    kit: "hardware",
    code: "HW-IRON-12",
    name: "Y12 Reinforcement Bar 12m",
    sku: "HW-IRON-12",
    categoryName: "Steel",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: "12 mm",
    minimumStock: 30,
    reorderLevel: 80,
    suggestedCost: 1200,
    suggestedSell: 1600,
  },
  {
    kit: "hardware",
    code: "HW-IRON-16",
    name: "Y16 Reinforcement Bar 12m",
    sku: "HW-IRON-16",
    categoryName: "Steel",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: "16 mm",
    minimumStock: 20,
    reorderLevel: 50,
    suggestedCost: 2100,
    suggestedSell: 2800,
  },
  {
    kit: "hardware",
    code: "HW-WIRE-MESH",
    name: "BRC Wire Mesh Sheet",
    sku: "HW-WIRE-MESH",
    categoryName: "Steel",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 1800,
    suggestedSell: 2500,
  },
  {
    kit: "hardware",
    code: "HW-BINDING-WIRE",
    name: "Binding Wire 25 kg",
    sku: "HW-BINDING-WIRE",
    categoryName: "Steel",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 5,
    reorderLevel: 15,
    suggestedCost: 4500,
    suggestedSell: 6000,
  },
  {
    kit: "hardware",
    code: "HW-TIMBER-2X4",
    name: "Timber 2x4 (per foot)",
    sku: "HW-TIMBER-2X4",
    categoryName: "Timber",
    stockUnitCode: "FT",
    salesUnitCode: "FT",
    purchaseUnitCode: "FT",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 100,
    reorderLevel: 300,
    suggestedCost: 35,
    suggestedSell: 55,
  },
  {
    kit: "hardware",
    code: "HW-TIMBER-2X6",
    name: "Timber 2x6 (per foot)",
    sku: "HW-TIMBER-2X6",
    categoryName: "Timber",
    stockUnitCode: "FT",
    salesUnitCode: "FT",
    purchaseUnitCode: "FT",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 80,
    reorderLevel: 200,
    suggestedCost: 55,
    suggestedSell: 85,
  },
  {
    kit: "hardware",
    code: "HW-PLY-8MM",
    name: "Plywood 8 mm Sheet",
    sku: "HW-PLY-8MM",
    categoryName: "Timber",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: "Standard sheet",
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 1800,
    suggestedSell: 2500,
  },
  {
    kit: "hardware",
    code: "HW-PLY-18MM",
    name: "Plywood 18 mm Sheet",
    sku: "HW-PLY-18MM",
    categoryName: "Timber",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 3500,
    suggestedSell: 4800,
  },
  {
    kit: "hardware",
    code: "HW-NAIL-3",
    name: "Wire Nails 3 inch (kg)",
    sku: "HW-NAIL-3",
    categoryName: "Fasteners",
    stockUnitCode: "KG",
    salesUnitCode: "KG",
    purchaseUnitCode: "KG",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 20,
    reorderLevel: 50,
    suggestedCost: 180,
    suggestedSell: 280,
  },
  {
    kit: "hardware",
    code: "HW-NAIL-4",
    name: "Wire Nails 4 inch (kg)",
    sku: "HW-NAIL-4",
    categoryName: "Fasteners",
    stockUnitCode: "KG",
    salesUnitCode: "KG",
    purchaseUnitCode: "KG",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 20,
    reorderLevel: 50,
    suggestedCost: 180,
    suggestedSell: 280,
  },
  {
    kit: "hardware",
    code: "HW-SCREW-PACK",
    name: "Wood Screws Assorted Pack",
    sku: "HW-SCREW-PACK",
    categoryName: "Fasteners",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "BOX",
    boxFactor: 50,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: "Box of 50",
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 350,
    suggestedSell: 550,
  },
  {
    kit: "hardware",
    code: "HW-BOLT-M12",
    name: "Bolt & Nut M12",
    sku: "HW-BOLT-M12",
    categoryName: "Fasteners",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "BOX",
    boxFactor: 25,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 50,
    reorderLevel: 150,
    suggestedCost: 40,
    suggestedSell: 80,
  },
  {
    kit: "hardware",
    code: "HW-HINGE-4",
    name: "Door Hinge 4 inch",
    sku: "HW-HINGE-4",
    categoryName: "Hardware Fittings",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 20,
    reorderLevel: 60,
    suggestedCost: 150,
    suggestedSell: 280,
  },
  {
    kit: "hardware",
    code: "HW-LOCK-PAD",
    name: "Padlock 40 mm",
    sku: "HW-LOCK-PAD",
    categoryName: "Hardware Fittings",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 250,
    suggestedSell: 450,
  },
  {
    kit: "hardware",
    code: "HW-LOCK-DOOR",
    name: "Mortice Door Lock",
    sku: "HW-LOCK-DOOR",
    categoryName: "Hardware Fittings",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 800,
    suggestedSell: 1400,
  },
  {
    kit: "hardware",
    code: "HW-HANDLE",
    name: "Door Handle Pair",
    sku: "HW-HANDLE",
    categoryName: "Hardware Fittings",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 450,
    suggestedSell: 800,
  },
  {
    kit: "hardware",
    code: "HW-PIPE-PVC-1",
    name: "PVC Pipe 1 inch (6m)",
    sku: "HW-PIPE-PVC-1",
    categoryName: "Plumbing",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 20,
    reorderLevel: 50,
    suggestedCost: 450,
    suggestedSell: 700,
  },
  {
    kit: "hardware",
    code: "HW-PIPE-PVC-1.5",
    name: "PVC Pipe 1.5 inch (6m)",
    sku: "HW-PIPE-PVC-1.5",
    categoryName: "Plumbing",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 650,
    suggestedSell: 1000,
  },
  {
    kit: "hardware",
    code: "HW-ELBOW-1",
    name: "PVC Elbow 1 inch",
    sku: "HW-ELBOW-1",
    categoryName: "Plumbing",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 50,
    reorderLevel: 150,
    suggestedCost: 30,
    suggestedSell: 60,
  },
  {
    kit: "hardware",
    code: "HW-TEE-1",
    name: "PVC Tee 1 inch",
    sku: "HW-TEE-1",
    categoryName: "Plumbing",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 40,
    reorderLevel: 120,
    suggestedCost: 40,
    suggestedSell: 80,
  },
  {
    kit: "hardware",
    code: "HW-TAP-BIB",
    name: "Bib Cock Tap",
    sku: "HW-TAP-BIB",
    categoryName: "Plumbing",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 350,
    suggestedSell: 650,
  },
  {
    kit: "hardware",
    code: "HW-BALL-VALVE",
    name: "Ball Valve 1 inch",
    sku: "HW-BALL-VALVE",
    categoryName: "Plumbing",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 12,
    reorderLevel: 30,
    suggestedCost: 450,
    suggestedSell: 800,
  },
  {
    kit: "hardware",
    code: "HW-TANK-1000",
    name: "Water Tank 1000 L",
    sku: "HW-TANK-1000",
    categoryName: "Plumbing",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 2,
    reorderLevel: 5,
    suggestedCost: 8500,
    suggestedSell: 12000,
  },
  {
    kit: "hardware",
    code: "HW-CABLE-2.5",
    name: "Electric Cable 2.5 mm (m)",
    sku: "HW-CABLE-2.5",
    categoryName: "Electrical",
    stockUnitCode: "M",
    salesUnitCode: "M",
    purchaseUnitCode: "M",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 100,
    reorderLevel: 300,
    suggestedCost: 80,
    suggestedSell: 130,
  },
  {
    kit: "hardware",
    code: "HW-CABLE-4",
    name: "Electric Cable 4 mm (m)",
    sku: "HW-CABLE-4",
    categoryName: "Electrical",
    stockUnitCode: "M",
    salesUnitCode: "M",
    purchaseUnitCode: "M",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 80,
    reorderLevel: 200,
    suggestedCost: 120,
    suggestedSell: 190,
  },
  {
    kit: "hardware",
    code: "HW-SWITCH",
    name: "Light Switch 1-gang",
    sku: "HW-SWITCH",
    categoryName: "Electrical",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 30,
    reorderLevel: 80,
    suggestedCost: 150,
    suggestedSell: 280,
  },
  {
    kit: "hardware",
    code: "HW-SOCKET",
    name: "13A Socket Outlet",
    sku: "HW-SOCKET",
    categoryName: "Electrical",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 25,
    reorderLevel: 60,
    suggestedCost: 250,
    suggestedSell: 450,
  },
  {
    kit: "hardware",
    code: "HW-BULB-LED",
    name: "LED Bulb 9W",
    sku: "HW-BULB-LED",
    categoryName: "Electrical",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "BOX",
    boxFactor: 10,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 40,
    reorderLevel: 100,
    suggestedCost: 120,
    suggestedSell: 250,
  },
  {
    kit: "hardware",
    code: "HW-MCB-32",
    name: "MCB 32A Single Pole",
    sku: "HW-MCB-32",
    categoryName: "Electrical",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 350,
    suggestedSell: 600,
  },
  {
    kit: "hardware",
    code: "HW-PAINT-WHT",
    name: "Emulsion Paint White 20 L",
    sku: "HW-PAINT-WHT",
    categoryName: "Paint",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 8,
    reorderLevel: 20,
    suggestedCost: 4500,
    suggestedSell: 6500,
  },
  {
    kit: "hardware",
    code: "HW-PAINT-EXT",
    name: "Exterior Paint 20 L",
    sku: "HW-PAINT-EXT",
    categoryName: "Paint",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 5,
    reorderLevel: 15,
    suggestedCost: 5500,
    suggestedSell: 7800,
  },
  {
    kit: "hardware",
    code: "HW-BRUSH-4",
    name: "Paint Brush 4 inch",
    sku: "HW-BRUSH-4",
    categoryName: "Paint",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 20,
    reorderLevel: 50,
    suggestedCost: 150,
    suggestedSell: 280,
  },
  {
    kit: "hardware",
    code: "HW-ROLLER",
    name: "Paint Roller Set",
    sku: "HW-ROLLER",
    categoryName: "Paint",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 350,
    suggestedSell: 600,
  },
  {
    kit: "hardware",
    code: "HW-THINNER",
    name: "Paint Thinner 5 L",
    sku: "HW-THINNER",
    categoryName: "Paint",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 800,
    suggestedSell: 1200,
  },
  {
    kit: "hardware",
    code: "HW-GLUE-WOOD",
    name: "Wood Glue 1 L",
    sku: "HW-GLUE-WOOD",
    categoryName: "Adhesives",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 12,
    reorderLevel: 30,
    suggestedCost: 450,
    suggestedSell: 750,
  },
  {
    kit: "hardware",
    code: "HW-SILICONE",
    name: "Silicone Sealant",
    sku: "HW-SILICONE",
    categoryName: "Adhesives",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 20,
    reorderLevel: 50,
    suggestedCost: 280,
    suggestedSell: 500,
  },
  {
    kit: "hardware",
    code: "HW-HAMMER",
    name: "Claw Hammer",
    sku: "HW-HAMMER",
    categoryName: "Tools",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 8,
    reorderLevel: 20,
    suggestedCost: 450,
    suggestedSell: 800,
  },
  {
    kit: "hardware",
    code: "HW-TAPE-M",
    name: "Measuring Tape 5 m",
    sku: "HW-TAPE-M",
    categoryName: "Tools",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 250,
    suggestedSell: 450,
  },
  {
    kit: "hardware",
    code: "HW-SPIRIT",
    name: "Spirit Level 60 cm",
    sku: "HW-SPIRIT",
    categoryName: "Tools",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 6,
    reorderLevel: 15,
    suggestedCost: 600,
    suggestedSell: 1100,
  },
  {
    kit: "hardware",
    code: "HW-SHOVEL",
    name: "Shovel",
    sku: "HW-SHOVEL",
    categoryName: "Tools",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 500,
    suggestedSell: 900,
  },
  {
    kit: "hardware",
    code: "HW-WHEELBAR",
    name: "Wheelbarrow",
    sku: "HW-WHEELBAR",
    categoryName: "Tools",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 3,
    reorderLevel: 8,
    suggestedCost: 3500,
    suggestedSell: 5500,
  },
  {
    kit: "hardware",
    code: "HW-ROOF-CGI",
    name: "CGI Roofing Sheet 30G",
    sku: "HW-ROOF-CGI",
    categoryName: "Roofing",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: "Standard length",
    minimumStock: 30,
    reorderLevel: 80,
    suggestedCost: 1200,
    suggestedSell: 1800,
  },
  {
    kit: "hardware",
    code: "HW-ROOF-RID",
    name: "Roof Ridge Cap",
    sku: "HW-ROOF-RID",
    categoryName: "Roofing",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 350,
    suggestedSell: 550,
  },
  {
    kit: "hardware",
    code: "HW-GUTTER",
    name: "Gutter Channel 6m",
    sku: "HW-GUTTER",
    categoryName: "Roofing",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 900,
    suggestedSell: 1400,
  },

  // ——— Agrovet ———

  {
    kit: "agrovet",
    code: "AV-DAP-50",
    name: "DAP Fertilizer 50 kg",
    sku: "AV-DAP-50",
    categoryName: "Fertilizers",
    stockUnitCode: "BAG",
    salesUnitCode: "BAG",
    purchaseUnitCode: "BAG",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 20,
    reorderLevel: 50,
    suggestedCost: 4500,
    suggestedSell: 5500,
  },
  {
    kit: "agrovet",
    code: "AV-CAN-50",
    name: "CAN Fertilizer 50 kg",
    sku: "AV-CAN-50",
    categoryName: "Fertilizers",
    stockUnitCode: "BAG",
    salesUnitCode: "BAG",
    purchaseUnitCode: "BAG",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 20,
    reorderLevel: 50,
    suggestedCost: 3200,
    suggestedSell: 4000,
  },
  {
    kit: "agrovet",
    code: "AV-UREA-50",
    name: "Urea 50 kg",
    sku: "AV-UREA-50",
    categoryName: "Fertilizers",
    stockUnitCode: "BAG",
    salesUnitCode: "BAG",
    purchaseUnitCode: "BAG",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 3800,
    suggestedSell: 4700,
  },
  {
    kit: "agrovet",
    code: "AV-NPK-50",
    name: "NPK 17:17:17 50 kg",
    sku: "AV-NPK-50",
    categoryName: "Fertilizers",
    stockUnitCode: "BAG",
    salesUnitCode: "BAG",
    purchaseUnitCode: "BAG",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 4200,
    suggestedSell: 5200,
  },
  {
    kit: "agrovet",
    code: "AV-FOLIAR-1L",
    name: "Foliar Feed 1 L",
    sku: "AV-FOLIAR-1L",
    categoryName: "Fertilizers",
    stockUnitCode: "BOT",
    salesUnitCode: "BOT",
    purchaseUnitCode: "BOT",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 20,
    reorderLevel: 50,
    suggestedCost: 450,
    suggestedSell: 750,
  },
  {
    kit: "agrovet",
    code: "AV-MANURE-BAG",
    name: "Organic Manure 50 kg",
    sku: "AV-MANURE-BAG",
    categoryName: "Fertilizers",
    stockUnitCode: "BAG",
    salesUnitCode: "BAG",
    purchaseUnitCode: "BAG",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 800,
    suggestedSell: 1200,
  },
  {
    kit: "agrovet",
    code: "AV-MAIZE-SEED",
    name: "Maize Seed Hybrid 2 kg",
    sku: "AV-MAIZE-SEED",
    categoryName: "Seeds",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 30,
    reorderLevel: 80,
    suggestedCost: 450,
    suggestedSell: 700,
  },
  {
    kit: "agrovet",
    code: "AV-BEAN-SEED",
    name: "Bean Seed 2 kg",
    sku: "AV-BEAN-SEED",
    categoryName: "Seeds",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 25,
    reorderLevel: 60,
    suggestedCost: 350,
    suggestedSell: 550,
  },
  {
    kit: "agrovet",
    code: "AV-VEG-SEED",
    name: "Vegetable Seed Assorted",
    sku: "AV-VEG-SEED",
    categoryName: "Seeds",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 40,
    reorderLevel: 100,
    suggestedCost: 150,
    suggestedSell: 300,
  },
  {
    kit: "agrovet",
    code: "AV-PASTURE",
    name: "Pasture Grass Seed 1 kg",
    sku: "AV-PASTURE",
    categoryName: "Seeds",
    stockUnitCode: "KG",
    salesUnitCode: "KG",
    purchaseUnitCode: "KG",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 800,
    suggestedSell: 1200,
  },
  {
    kit: "agrovet",
    code: "AV-HERB-ROUND",
    name: "Glyphosate Herbicide 1 L",
    sku: "AV-HERB-ROUND",
    categoryName: "Agrochemicals",
    stockUnitCode: "BOT",
    salesUnitCode: "BOT",
    purchaseUnitCode: "BOT",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 1200,
    suggestedSell: 1800,
  },
  {
    kit: "agrovet",
    code: "AV-HERB-2-4D",
    name: "2,4-D Amine 1 L",
    sku: "AV-HERB-2-4D",
    categoryName: "Agrochemicals",
    stockUnitCode: "BOT",
    salesUnitCode: "BOT",
    purchaseUnitCode: "BOT",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 12,
    reorderLevel: 30,
    suggestedCost: 900,
    suggestedSell: 1400,
  },
  {
    kit: "agrovet",
    code: "AV-INSECT-1L",
    name: "Lambda Cyhalothrin 1 L",
    sku: "AV-INSECT-1L",
    categoryName: "Agrochemicals",
    stockUnitCode: "BOT",
    salesUnitCode: "BOT",
    purchaseUnitCode: "BOT",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 12,
    reorderLevel: 30,
    suggestedCost: 1500,
    suggestedSell: 2300,
  },
  {
    kit: "agrovet",
    code: "AV-FUNG-1L",
    name: "Mancozeb Fungicide 1 kg",
    sku: "AV-FUNG-1L",
    categoryName: "Agrochemicals",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 800,
    suggestedSell: 1300,
  },
  {
    kit: "agrovet",
    code: "AV-ACAR",
    name: "Acaricide 100 mL",
    sku: "AV-ACAR",
    categoryName: "Agrochemicals",
    stockUnitCode: "BOT",
    salesUnitCode: "BOT",
    purchaseUnitCode: "BOT",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 600,
    suggestedSell: 1000,
  },
  {
    kit: "agrovet",
    code: "AV-DEWORM-SHEEP",
    name: "Sheep/Goat Dewormer 1 L",
    sku: "AV-DEWORM-SHEEP",
    categoryName: "Animal Health",
    stockUnitCode: "BOT",
    salesUnitCode: "BOT",
    purchaseUnitCode: "BOT",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 800,
    suggestedSell: 1300,
  },
  {
    kit: "agrovet",
    code: "AV-DEWORM-CATTLE",
    name: "Cattle Dewormer 1 L",
    sku: "AV-DEWORM-CATTLE",
    categoryName: "Animal Health",
    stockUnitCode: "BOT",
    salesUnitCode: "BOT",
    purchaseUnitCode: "BOT",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 12,
    reorderLevel: 30,
    suggestedCost: 1200,
    suggestedSell: 1900,
  },
  {
    kit: "agrovet",
    code: "AV-TICK-DIP",
    name: "Tick Grease / Dip 1 L",
    sku: "AV-TICK-DIP",
    categoryName: "Animal Health",
    stockUnitCode: "BOT",
    salesUnitCode: "BOT",
    purchaseUnitCode: "BOT",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 12,
    reorderLevel: 30,
    suggestedCost: 900,
    suggestedSell: 1500,
  },
  {
    kit: "agrovet",
    code: "AV-ANTIBIO-VET",
    name: "Oxytetracycline Inject 100 mL",
    sku: "AV-ANTIBIO-VET",
    categoryName: "Animal Health",
    stockUnitCode: "BOT",
    salesUnitCode: "BOT",
    purchaseUnitCode: "BOT",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 450,
    suggestedSell: 800,
  },
  {
    kit: "agrovet",
    code: "AV-MULTIVIT-VET",
    name: "Livestock Multivitamin 100 mL",
    sku: "AV-MULTIVIT-VET",
    categoryName: "Animal Health",
    stockUnitCode: "BOT",
    salesUnitCode: "BOT",
    purchaseUnitCode: "BOT",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 350,
    suggestedSell: 650,
  },
  {
    kit: "agrovet",
    code: "AV-MASTITIS",
    name: "Mastitis Tube",
    sku: "AV-MASTITIS",
    categoryName: "Animal Health",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 30,
    reorderLevel: 80,
    suggestedCost: 150,
    suggestedSell: 280,
  },
  {
    kit: "agrovet",
    code: "AV-CALCIUM-INJ",
    name: "Calcium Injection 100 mL",
    sku: "AV-CALCIUM-INJ",
    categoryName: "Animal Health",
    stockUnitCode: "BOT",
    salesUnitCode: "BOT",
    purchaseUnitCode: "BOT",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 500,
    suggestedSell: 900,
  },
  {
    kit: "agrovet",
    code: "AV-FEED-DAIRY",
    name: "Dairy Meal 50 kg",
    sku: "AV-FEED-DAIRY",
    categoryName: "Animal Feeds",
    stockUnitCode: "BAG",
    salesUnitCode: "BAG",
    purchaseUnitCode: "BAG",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 20,
    reorderLevel: 50,
    suggestedCost: 2800,
    suggestedSell: 3500,
  },
  {
    kit: "agrovet",
    code: "AV-FEED-LAYER",
    name: "Layers Mash 50 kg",
    sku: "AV-FEED-LAYER",
    categoryName: "Animal Feeds",
    stockUnitCode: "BAG",
    salesUnitCode: "BAG",
    purchaseUnitCode: "BAG",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 3200,
    suggestedSell: 4000,
  },
  {
    kit: "agrovet",
    code: "AV-FEED-BROILER",
    name: "Broiler Starter 50 kg",
    sku: "AV-FEED-BROILER",
    categoryName: "Animal Feeds",
    stockUnitCode: "BAG",
    salesUnitCode: "BAG",
    purchaseUnitCode: "BAG",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 3500,
    suggestedSell: 4300,
  },
  {
    kit: "agrovet",
    code: "AV-FEED-PIG",
    name: "Pig Feed 50 kg",
    sku: "AV-FEED-PIG",
    categoryName: "Animal Feeds",
    stockUnitCode: "BAG",
    salesUnitCode: "BAG",
    purchaseUnitCode: "BAG",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 3000,
    suggestedSell: 3800,
  },
  {
    kit: "agrovet",
    code: "AV-FEED-FISH",
    name: "Fish Feed 25 kg",
    sku: "AV-FEED-FISH",
    categoryName: "Animal Feeds",
    stockUnitCode: "BAG",
    salesUnitCode: "BAG",
    purchaseUnitCode: "BAG",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 2500,
    suggestedSell: 3200,
  },
  {
    kit: "agrovet",
    code: "AV-CHICK-MASH",
    name: "Chick Mash 50 kg",
    sku: "AV-CHICK-MASH",
    categoryName: "Animal Feeds",
    stockUnitCode: "BAG",
    salesUnitCode: "BAG",
    purchaseUnitCode: "BAG",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 12,
    reorderLevel: 30,
    suggestedCost: 3400,
    suggestedSell: 4200,
  },
  {
    kit: "agrovet",
    code: "AV-SALT-LICK",
    name: "Mineral Salt Lick",
    sku: "AV-SALT-LICK",
    categoryName: "Animal Feeds",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 25,
    reorderLevel: 60,
    suggestedCost: 250,
    suggestedSell: 450,
  },
  {
    kit: "agrovet",
    code: "AV-MILK-CAN",
    name: "Milk Can 20 L",
    sku: "AV-MILK-CAN",
    categoryName: "Farm Equipment",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 5,
    reorderLevel: 12,
    suggestedCost: 2500,
    suggestedSell: 4000,
  },
  {
    kit: "agrovet",
    code: "AV-SPRRAYER",
    name: "Knapsack Sprayer 16 L",
    sku: "AV-SPRRAYER",
    categoryName: "Farm Equipment",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 5,
    reorderLevel: 12,
    suggestedCost: 3500,
    suggestedSell: 5500,
  },
  {
    kit: "agrovet",
    code: "AV-HOE",
    name: "Jembe / Hoe",
    sku: "AV-HOE",
    categoryName: "Farm Equipment",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 450,
    suggestedSell: 800,
  },
  {
    kit: "agrovet",
    code: "AV-PANGA",
    name: "Panga / Machete",
    sku: "AV-PANGA",
    categoryName: "Farm Equipment",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 350,
    suggestedSell: 600,
  },
  {
    kit: "agrovet",
    code: "AV-FORK",
    name: "Garden Fork",
    sku: "AV-FORK",
    categoryName: "Farm Equipment",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 500,
    suggestedSell: 900,
  },
  {
    kit: "agrovet",
    code: "AV-WATERING",
    name: "Watering Can 10 L",
    sku: "AV-WATERING",
    categoryName: "Farm Equipment",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 400,
    suggestedSell: 700,
  },
  {
    kit: "agrovet",
    code: "AV-CHICK-WIRE",
    name: "Chicken Wire Mesh (m)",
    sku: "AV-CHICK-WIRE",
    categoryName: "Farm Equipment",
    stockUnitCode: "M",
    salesUnitCode: "M",
    purchaseUnitCode: "M",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 50,
    reorderLevel: 150,
    suggestedCost: 250,
    suggestedSell: 400,
  },
  {
    kit: "agrovet",
    code: "AV-EAR-TAG",
    name: "Livestock Ear Tags (pair)",
    sku: "AV-EAR-TAG",
    categoryName: "Farm Equipment",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 40,
    reorderLevel: 100,
    suggestedCost: 80,
    suggestedSell: 150,
  },
  {
    kit: "agrovet",
    code: "AV-DRENCH-GUN",
    name: "Drenching Gun",
    sku: "AV-DRENCH-GUN",
    categoryName: "Farm Equipment",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 5,
    reorderLevel: 12,
    suggestedCost: 1200,
    suggestedSell: 2000,
  },
  {
    kit: "agrovet",
    code: "AV-SYRINGE-VET",
    name: "Vet Syringe 20 mL",
    sku: "AV-SYRINGE-VET",
    categoryName: "Farm Equipment",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 30,
    reorderLevel: 80,
    suggestedCost: 80,
    suggestedSell: 150,
  },
  {
    kit: "agrovet",
    code: "AV-GLOVES",
    name: "Farm Gloves Pair",
    sku: "AV-GLOVES",
    categoryName: "Farm Equipment",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 20,
    reorderLevel: 50,
    suggestedCost: 150,
    suggestedSell: 280,
  },

  // ——— Motorbike ———

  {
    kit: "motorbike",
    code: "MB-OF-HF204",
    name: "Oil Filter HF204",
    sku: "MB-OF-HF204",
    categoryName: "Engine Filters",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: "OEM",
    description: "Common 150cc filter",
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 180,
    suggestedSell: 350,
  },
  {
    kit: "motorbike",
    code: "MB-AF-01",
    name: "Air Filter Element",
    sku: "MB-AF-01",
    categoryName: "Engine Filters",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 300,
    suggestedSell: 550,
  },
  {
    kit: "motorbike",
    code: "MB-PLUG-CR7",
    name: "Spark Plug CR7HSA",
    sku: "MB-PLUG-CR7",
    categoryName: "Ignition",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: "NGK",
    description: null,
    minimumStock: 30,
    reorderLevel: 80,
    suggestedCost: 120,
    suggestedSell: 250,
  },
  {
    kit: "motorbike",
    code: "MB-PLUG-C7",
    name: "Spark Plug C7HSA",
    sku: "MB-PLUG-C7",
    categoryName: "Ignition",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: "NGK",
    description: null,
    minimumStock: 30,
    reorderLevel: 80,
    suggestedCost: 100,
    suggestedSell: 220,
  },
  {
    kit: "motorbike",
    code: "MB-CDI-6P",
    name: "CDI Unit 6-Pin",
    sku: "MB-CDI-6P",
    categoryName: "Electrical",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 8,
    reorderLevel: 20,
    suggestedCost: 800,
    suggestedSell: 1500,
  },
  {
    kit: "motorbike",
    code: "MB-BAT-12V5",
    name: "Battery 12V 5Ah",
    sku: "MB-BAT-12V5",
    categoryName: "Electrical",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: "Yuasa-type",
    description: null,
    minimumStock: 8,
    reorderLevel: 20,
    suggestedCost: 3500,
    suggestedSell: 5500,
  },
  {
    kit: "motorbike",
    code: "MB-BULB-H4",
    name: "Headlight Bulb H4 12V",
    sku: "MB-BULB-H4",
    categoryName: "Electrical",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 20,
    reorderLevel: 50,
    suggestedCost: 200,
    suggestedSell: 400,
  },
  {
    kit: "motorbike",
    code: "MB-REG-RECT",
    name: "Regulator Rectifier",
    sku: "MB-REG-RECT",
    categoryName: "Electrical",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 6,
    reorderLevel: 15,
    suggestedCost: 1200,
    suggestedSell: 2200,
  },
  {
    kit: "motorbike",
    code: "MB-BRK-F",
    name: "Brake Shoe Set Front",
    sku: "MB-BRK-F",
    categoryName: "Brakes",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 450,
    suggestedSell: 900,
  },
  {
    kit: "motorbike",
    code: "MB-BRK-R",
    name: "Brake Shoe Set Rear",
    sku: "MB-BRK-R",
    categoryName: "Brakes",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 450,
    suggestedSell: 900,
  },
  {
    kit: "motorbike",
    code: "MB-BRK-PAD",
    name: "Disc Brake Pads Pair",
    sku: "MB-BRK-PAD",
    categoryName: "Brakes",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 12,
    reorderLevel: 30,
    suggestedCost: 600,
    suggestedSell: 1200,
  },
  {
    kit: "motorbike",
    code: "MB-BRK-CBL",
    name: "Brake Cable",
    sku: "MB-BRK-CBL",
    categoryName: "Controls",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 20,
    reorderLevel: 50,
    suggestedCost: 250,
    suggestedSell: 500,
  },
  {
    kit: "motorbike",
    code: "MB-CLT-CBL",
    name: "Clutch Cable",
    sku: "MB-CLT-CBL",
    categoryName: "Controls",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 20,
    reorderLevel: 50,
    suggestedCost: 250,
    suggestedSell: 500,
  },
  {
    kit: "motorbike",
    code: "MB-THR-CBL",
    name: "Throttle Cable",
    sku: "MB-THR-CBL",
    categoryName: "Controls",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 220,
    suggestedSell: 450,
  },
  {
    kit: "motorbike",
    code: "MB-CHN-428",
    name: "Drive Chain 428H 120L",
    sku: "MB-CHN-428",
    categoryName: "Transmission",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: "DID-type",
    description: null,
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 1200,
    suggestedSell: 2200,
  },
  {
    kit: "motorbike",
    code: "MB-SPR-F14",
    name: "Sprocket Front 14T 428",
    sku: "MB-SPR-F14",
    categoryName: "Transmission",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 12,
    reorderLevel: 30,
    suggestedCost: 350,
    suggestedSell: 700,
  },
  {
    kit: "motorbike",
    code: "MB-SPR-R42",
    name: "Sprocket Rear 42T 428",
    sku: "MB-SPR-R42",
    categoryName: "Transmission",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 800,
    suggestedSell: 1500,
  },
  {
    kit: "motorbike",
    code: "MB-CLUTCH-PL",
    name: "Clutch Plate Set",
    sku: "MB-CLUTCH-PL",
    categoryName: "Transmission",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 8,
    reorderLevel: 20,
    suggestedCost: 1500,
    suggestedSell: 2800,
  },
  {
    kit: "motorbike",
    code: "MB-OIL-20W50",
    name: "Engine Oil 20W-50 1L",
    sku: "MB-OIL-20W50",
    categoryName: "Lubricants",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 25,
    reorderLevel: 60,
    suggestedCost: 450,
    suggestedSell: 800,
  },
  {
    kit: "motorbike",
    code: "MB-OIL-10W40",
    name: "Engine Oil 10W-40 1L",
    sku: "MB-OIL-10W40",
    categoryName: "Lubricants",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 20,
    reorderLevel: 50,
    suggestedCost: 550,
    suggestedSell: 950,
  },
  {
    kit: "motorbike",
    code: "MB-GEAR-OIL",
    name: "Gear Oil 1L",
    sku: "MB-GEAR-OIL",
    categoryName: "Lubricants",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 400,
    suggestedSell: 700,
  },
  {
    kit: "motorbike",
    code: "MB-BRKFL",
    name: "Brake Fluid DOT 4 500ml",
    sku: "MB-BRKFL",
    categoryName: "Lubricants",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 400,
    suggestedSell: 700,
  },
  {
    kit: "motorbike",
    code: "MB-TYRE-275",
    name: "Tyre 2.75-18",
    sku: "MB-TYRE-275",
    categoryName: "Tyres & Tubes",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 2800,
    suggestedSell: 4500,
  },
  {
    kit: "motorbike",
    code: "MB-TYRE-300",
    name: "Tyre 3.00-18",
    sku: "MB-TYRE-300",
    categoryName: "Tyres & Tubes",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 8,
    reorderLevel: 20,
    suggestedCost: 3200,
    suggestedSell: 5000,
  },
  {
    kit: "motorbike",
    code: "MB-TUBE-275",
    name: "Inner Tube 2.75-18",
    sku: "MB-TUBE-275",
    categoryName: "Tyres & Tubes",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 600,
    suggestedSell: 1100,
  },
  {
    kit: "motorbike",
    code: "MB-RIM-18",
    name: "Wheel Rim 18 inch",
    sku: "MB-RIM-18",
    categoryName: "Tyres & Tubes",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 5,
    reorderLevel: 12,
    suggestedCost: 2500,
    suggestedSell: 4000,
  },
  {
    kit: "motorbike",
    code: "MB-MIR-PAIR",
    name: "Side Mirror Pair",
    sku: "MB-MIR-PAIR",
    categoryName: "Body",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 12,
    reorderLevel: 30,
    suggestedCost: 800,
    suggestedSell: 1400,
  },
  {
    kit: "motorbike",
    code: "MB-GRP-01",
    name: "Hand Grip Pair",
    sku: "MB-GRP-01",
    categoryName: "Body",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 20,
    reorderLevel: 50,
    suggestedCost: 200,
    suggestedSell: 400,
  },
  {
    kit: "motorbike",
    code: "MB-LEVER-SET",
    name: "Brake/Clutch Lever Set",
    sku: "MB-LEVER-SET",
    categoryName: "Body",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 12,
    reorderLevel: 30,
    suggestedCost: 450,
    suggestedSell: 900,
  },
  {
    kit: "motorbike",
    code: "MB-CHAIN-CASE",
    name: "Chain Cover",
    sku: "MB-CHAIN-CASE",
    categoryName: "Body",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 8,
    reorderLevel: 20,
    suggestedCost: 600,
    suggestedSell: 1100,
  },
  {
    kit: "motorbike",
    code: "MB-CARB-KIT",
    name: "Carburetor Rebuild Kit",
    sku: "MB-CARB-KIT",
    categoryName: "Engine",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 800,
    suggestedSell: 1500,
  },
  {
    kit: "motorbike",
    code: "MB-GASKET-SET",
    name: "Engine Gasket Set",
    sku: "MB-GASKET-SET",
    categoryName: "Engine",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 700,
    suggestedSell: 1300,
  },
  {
    kit: "motorbike",
    code: "MB-PISTON-KIT",
    name: "Piston Kit 150cc",
    sku: "MB-PISTON-KIT",
    categoryName: "Engine",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 6,
    reorderLevel: 15,
    suggestedCost: 2500,
    suggestedSell: 4500,
  },
  {
    kit: "motorbike",
    code: "MB-VALVE-SET",
    name: "Valve Set Intake/Exhaust",
    sku: "MB-VALVE-SET",
    categoryName: "Engine",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 8,
    reorderLevel: 20,
    suggestedCost: 900,
    suggestedSell: 1800,
  },
  {
    kit: "motorbike",
    code: "MB-SHOCK-R",
    name: "Rear Shock Absorber",
    sku: "MB-SHOCK-R",
    categoryName: "Suspension",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 6,
    reorderLevel: 15,
    suggestedCost: 2200,
    suggestedSell: 4000,
  },
  {
    kit: "motorbike",
    code: "MB-FORK-SEAL",
    name: "Front Fork Seal Pair",
    sku: "MB-FORK-SEAL",
    categoryName: "Suspension",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 400,
    suggestedSell: 800,
  },
  {
    kit: "motorbike",
    code: "MB-BEARING-SW",
    name: "Steering Bearing Set",
    sku: "MB-BEARING-SW",
    categoryName: "Suspension",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 8,
    reorderLevel: 20,
    suggestedCost: 600,
    suggestedSell: 1200,
  },
  {
    kit: "motorbike",
    code: "UNIT-BOXER-150",
    name: "Boxer 150 Commuter (unit)",
    sku: "UNIT-BOXER-150",
    categoryName: "Complete Units",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: true,
    trackBatch: false,
    trackExpiry: false,
    productBrand: "Bajaj",
    description: "Serialized chassis/engine",
    minimumStock: 1,
    reorderLevel: 3,
    suggestedCost: 185000,
    suggestedSell: 245000,
  },
  {
    kit: "motorbike",
    code: "UNIT-TVS-HLX150",
    name: "TVS HLX 150 (unit)",
    sku: "UNIT-TVS-HLX150",
    categoryName: "Complete Units",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: true,
    trackBatch: false,
    trackExpiry: false,
    productBrand: "TVS",
    description: "Serialized chassis/engine",
    minimumStock: 1,
    reorderLevel: 3,
    suggestedCost: 175000,
    suggestedSell: 235000,
  },
  {
    kit: "motorbike",
    code: "UNIT-HONDA-ACE",
    name: "Honda Ace 125 (unit)",
    sku: "UNIT-HONDA-ACE",
    categoryName: "Complete Units",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: true,
    trackBatch: false,
    trackExpiry: false,
    productBrand: "Honda",
    description: "Serialized chassis/engine",
    minimumStock: 1,
    reorderLevel: 2,
    suggestedCost: 195000,
    suggestedSell: 260000,
  },
  {
    kit: "motorbike",
    code: "UNIT-BAJAJ-RE",
    name: "Bajaj RE 3-Wheeler (unit)",
    sku: "UNIT-BAJAJ-RE",
    categoryName: "Complete Units",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: true,
    trackBatch: false,
    trackExpiry: false,
    productBrand: "Bajaj",
    description: "Serialized chassis/engine",
    minimumStock: 1,
    reorderLevel: 2,
    suggestedCost: 520000,
    suggestedSell: 680000,
  },
  {
    kit: "motorbike",
    code: "UNIT-APE-CITY",
    name: "Piaggio Ape City (unit)",
    sku: "UNIT-APE-CITY",
    categoryName: "Complete Units",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: true,
    trackBatch: false,
    trackExpiry: false,
    productBrand: "Piaggio",
    description: "Serialized chassis/engine",
    minimumStock: 1,
    reorderLevel: 2,
    suggestedCost: 480000,
    suggestedSell: 620000,
  },
  {
    kit: "motorbike",
    code: "MB-3W-BELT",
    name: "3-Wheeler Drive Belt",
    sku: "MB-3W-BELT",
    categoryName: "3-Wheeler Parts",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 8,
    reorderLevel: 20,
    suggestedCost: 2200,
    suggestedSell: 3500,
  },
  {
    kit: "motorbike",
    code: "MB-3W-BRK-CBL",
    name: "3-Wheeler Brake Cable",
    sku: "MB-3W-BRK-CBL",
    categoryName: "3-Wheeler Parts",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 500,
    suggestedSell: 900,
  },
  {
    kit: "motorbike",
    code: "MB-3W-CABLE",
    name: "3-Wheeler Control Cable",
    sku: "MB-3W-CABLE",
    categoryName: "3-Wheeler Parts",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 450,
    suggestedSell: 850,
  },

  // ——— Auto ———

  {
    kit: "auto",
    code: "AP-OF-SPIN",
    name: "Spin-On Oil Filter",
    sku: "AP-OF-SPIN",
    categoryName: "Filters",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 20,
    reorderLevel: 50,
    suggestedCost: 450,
    suggestedSell: 900,
  },
  {
    kit: "auto",
    code: "AP-AF-PANEL",
    name: "Panel Air Filter",
    sku: "AP-AF-PANEL",
    categoryName: "Filters",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 600,
    suggestedSell: 1200,
  },
  {
    kit: "auto",
    code: "AP-CABIN-F",
    name: "Cabin Pollen Filter",
    sku: "AP-CABIN-F",
    categoryName: "Filters",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 12,
    reorderLevel: 30,
    suggestedCost: 800,
    suggestedSell: 1500,
  },
  {
    kit: "auto",
    code: "AP-FUEL-F",
    name: "Fuel Filter",
    sku: "AP-FUEL-F",
    categoryName: "Filters",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 700,
    suggestedSell: 1400,
  },
  {
    kit: "auto",
    code: "AP-SPARK-IR",
    name: "Iridium Spark Plug",
    sku: "AP-SPARK-IR",
    categoryName: "Ignition",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: "NGK-type",
    description: null,
    minimumStock: 25,
    reorderLevel: 60,
    suggestedCost: 450,
    suggestedSell: 900,
  },
  {
    kit: "auto",
    code: "AP-SPARK-STD",
    name: "Standard Spark Plug",
    sku: "AP-SPARK-STD",
    categoryName: "Ignition",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 40,
    reorderLevel: 100,
    suggestedCost: 150,
    suggestedSell: 350,
  },
  {
    kit: "auto",
    code: "AP-IGN-COIL",
    name: "Ignition Coil",
    sku: "AP-IGN-COIL",
    categoryName: "Ignition",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 6,
    reorderLevel: 15,
    suggestedCost: 2500,
    suggestedSell: 4500,
  },
  {
    kit: "auto",
    code: "AP-BAT-12V45",
    name: "Car Battery 12V 45Ah",
    sku: "AP-BAT-12V45",
    categoryName: "Electrical",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 5,
    reorderLevel: 12,
    suggestedCost: 8500,
    suggestedSell: 12000,
  },
  {
    kit: "auto",
    code: "AP-BAT-12V70",
    name: "Car Battery 12V 70Ah",
    sku: "AP-BAT-12V70",
    categoryName: "Electrical",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 4,
    reorderLevel: 10,
    suggestedCost: 12000,
    suggestedSell: 16500,
  },
  {
    kit: "auto",
    code: "AP-ALT-BRUSH",
    name: "Alternator Brush Set",
    sku: "AP-ALT-BRUSH",
    categoryName: "Electrical",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 400,
    suggestedSell: 800,
  },
  {
    kit: "auto",
    code: "AP-STARTER",
    name: "Starter Motor (reman)",
    sku: "AP-STARTER",
    categoryName: "Electrical",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 3,
    reorderLevel: 8,
    suggestedCost: 8000,
    suggestedSell: 14000,
  },
  {
    kit: "auto",
    code: "AP-BULB-H4",
    name: "Headlamp Bulb H4",
    sku: "AP-BULB-H4",
    categoryName: "Electrical",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 20,
    reorderLevel: 50,
    suggestedCost: 250,
    suggestedSell: 500,
  },
  {
    kit: "auto",
    code: "AP-BULB-H7",
    name: "Headlamp Bulb H7",
    sku: "AP-BULB-H7",
    categoryName: "Electrical",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 20,
    reorderLevel: 50,
    suggestedCost: 280,
    suggestedSell: 550,
  },
  {
    kit: "auto",
    code: "AP-PAD-FRONT",
    name: "Brake Pads Front",
    sku: "AP-PAD-FRONT",
    categoryName: "Brakes",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 12,
    reorderLevel: 30,
    suggestedCost: 1800,
    suggestedSell: 3500,
  },
  {
    kit: "auto",
    code: "AP-PAD-REAR",
    name: "Brake Pads Rear",
    sku: "AP-PAD-REAR",
    categoryName: "Brakes",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 12,
    reorderLevel: 30,
    suggestedCost: 1500,
    suggestedSell: 3000,
  },
  {
    kit: "auto",
    code: "AP-DISC-FRONT",
    name: "Brake Disc Front",
    sku: "AP-DISC-FRONT",
    categoryName: "Brakes",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 6,
    reorderLevel: 15,
    suggestedCost: 4500,
    suggestedSell: 7500,
  },
  {
    kit: "auto",
    code: "AP-BRK-SHOE",
    name: "Brake Shoe Set",
    sku: "AP-BRK-SHOE",
    categoryName: "Brakes",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 1200,
    suggestedSell: 2400,
  },
  {
    kit: "auto",
    code: "AP-BRKFL-DOT4",
    name: "Brake Fluid DOT 4 1L",
    sku: "AP-BRKFL-DOT4",
    categoryName: "Fluids",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 600,
    suggestedSell: 1100,
  },
  {
    kit: "auto",
    code: "AP-COOLANT",
    name: "Engine Coolant 1L",
    sku: "AP-COOLANT",
    categoryName: "Fluids",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 20,
    reorderLevel: 50,
    suggestedCost: 450,
    suggestedSell: 800,
  },
  {
    kit: "auto",
    code: "AP-ATF",
    name: "ATF Transmission Fluid 1L",
    sku: "AP-ATF",
    categoryName: "Fluids",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 12,
    reorderLevel: 30,
    suggestedCost: 800,
    suggestedSell: 1400,
  },
  {
    kit: "auto",
    code: "AP-OIL-5W30",
    name: "Engine Oil 5W-30 1L",
    sku: "AP-OIL-5W30",
    categoryName: "Lubricants",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 25,
    reorderLevel: 60,
    suggestedCost: 900,
    suggestedSell: 1500,
  },
  {
    kit: "auto",
    code: "AP-OIL-10W40",
    name: "Engine Oil 10W-40 4L",
    sku: "AP-OIL-10W40",
    categoryName: "Lubricants",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 2800,
    suggestedSell: 4500,
  },
  {
    kit: "auto",
    code: "AP-OIL-20W50",
    name: "Engine Oil 20W-50 4L",
    sku: "AP-OIL-20W50",
    categoryName: "Lubricants",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 2200,
    suggestedSell: 3600,
  },
  {
    kit: "auto",
    code: "AP-GEAR-80W90",
    name: "Gear Oil 80W-90 1L",
    sku: "AP-GEAR-80W90",
    categoryName: "Lubricants",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 12,
    reorderLevel: 30,
    suggestedCost: 700,
    suggestedSell: 1200,
  },
  {
    kit: "auto",
    code: "AP-SHOCK-F",
    name: "Shock Absorber Front",
    sku: "AP-SHOCK-F",
    categoryName: "Suspension",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 6,
    reorderLevel: 15,
    suggestedCost: 3500,
    suggestedSell: 6000,
  },
  {
    kit: "auto",
    code: "AP-SHOCK-R",
    name: "Shock Absorber Rear",
    sku: "AP-SHOCK-R",
    categoryName: "Suspension",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 6,
    reorderLevel: 15,
    suggestedCost: 3200,
    suggestedSell: 5500,
  },
  {
    kit: "auto",
    code: "AP-BALL-JOINT",
    name: "Ball Joint",
    sku: "AP-BALL-JOINT",
    categoryName: "Suspension",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 8,
    reorderLevel: 20,
    suggestedCost: 1500,
    suggestedSell: 2800,
  },
  {
    kit: "auto",
    code: "AP-TIE-ROD",
    name: "Tie Rod End",
    sku: "AP-TIE-ROD",
    categoryName: "Suspension",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 8,
    reorderLevel: 20,
    suggestedCost: 1200,
    suggestedSell: 2400,
  },
  {
    kit: "auto",
    code: "AP-BUSH-KIT",
    name: "Control Arm Bush Kit",
    sku: "AP-BUSH-KIT",
    categoryName: "Suspension",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 8,
    reorderLevel: 20,
    suggestedCost: 1800,
    suggestedSell: 3200,
  },
  {
    kit: "auto",
    code: "AP-TYRE-185",
    name: "Tyre 185/65 R15",
    sku: "AP-TYRE-185",
    categoryName: "Tyres",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 8,
    reorderLevel: 20,
    suggestedCost: 6500,
    suggestedSell: 9500,
  },
  {
    kit: "auto",
    code: "AP-TYRE-195",
    name: "Tyre 195/65 R15",
    sku: "AP-TYRE-195",
    categoryName: "Tyres",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 8,
    reorderLevel: 20,
    suggestedCost: 7000,
    suggestedSell: 10500,
  },
  {
    kit: "auto",
    code: "AP-TYRE-205",
    name: "Tyre 205/55 R16",
    sku: "AP-TYRE-205",
    categoryName: "Tyres",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 6,
    reorderLevel: 15,
    suggestedCost: 8500,
    suggestedSell: 12500,
  },
  {
    kit: "auto",
    code: "AP-WIPER",
    name: "Wiper Blade Pair",
    sku: "AP-WIPER",
    categoryName: "Body",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 15,
    reorderLevel: 40,
    suggestedCost: 600,
    suggestedSell: 1200,
  },
  {
    kit: "auto",
    code: "AP-MIRROR",
    name: "Side Mirror Assembly",
    sku: "AP-MIRROR",
    categoryName: "Body",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 6,
    reorderLevel: 15,
    suggestedCost: 2500,
    suggestedSell: 4500,
  },
  {
    kit: "auto",
    code: "AP-BELT-TIMING",
    name: "Timing Belt",
    sku: "AP-BELT-TIMING",
    categoryName: "Engine",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 8,
    reorderLevel: 20,
    suggestedCost: 2200,
    suggestedSell: 4000,
  },
  {
    kit: "auto",
    code: "AP-BELT-ALT",
    name: "Alternator Belt",
    sku: "AP-BELT-ALT",
    categoryName: "Engine",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 12,
    reorderLevel: 30,
    suggestedCost: 800,
    suggestedSell: 1500,
  },
  {
    kit: "auto",
    code: "AP-WATER-PUMP",
    name: "Water Pump",
    sku: "AP-WATER-PUMP",
    categoryName: "Engine",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 5,
    reorderLevel: 12,
    suggestedCost: 3500,
    suggestedSell: 6500,
  },
  {
    kit: "auto",
    code: "AP-THERMOSTAT",
    name: "Thermostat",
    sku: "AP-THERMOSTAT",
    categoryName: "Engine",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 600,
    suggestedSell: 1200,
  },
  {
    kit: "auto",
    code: "AP-CLUTCH-KIT",
    name: "Clutch Kit 3-piece",
    sku: "AP-CLUTCH-KIT",
    categoryName: "Transmission",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 4,
    reorderLevel: 10,
    suggestedCost: 8500,
    suggestedSell: 14000,
  },
  {
    kit: "auto",
    code: "AP-CV-JOINT",
    name: "CV Joint",
    sku: "AP-CV-JOINT",
    categoryName: "Transmission",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 5,
    reorderLevel: 12,
    suggestedCost: 4500,
    suggestedSell: 8000,
  },
  {
    kit: "auto",
    code: "AP-RAD-HOSE",
    name: "Radiator Hose Set",
    sku: "AP-RAD-HOSE",
    categoryName: "Cooling",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 10,
    reorderLevel: 25,
    suggestedCost: 900,
    suggestedSell: 1800,
  },
  {
    kit: "auto",
    code: "AP-RAD-CAP",
    name: "Radiator Cap",
    sku: "AP-RAD-CAP",
    categoryName: "Cooling",
    stockUnitCode: "PCS",
    salesUnitCode: "PCS",
    purchaseUnitCode: "PCS",
    boxFactor: null,
    serialized: false,
    trackBatch: false,
    trackExpiry: false,
    productBrand: null,
    description: null,
    minimumStock: 12,
    reorderLevel: 30,
    suggestedCost: 350,
    suggestedSell: 700,
  },
];

export function listIndustryStarterByKit(
  kit: IndustryStarterKitId,
): IndustryStarterProduct[] {
  return DEFAULT_INDUSTRY_STARTER_PRODUCTS.filter((p) => p.kit === kit);
}

export function getIndustryStarterByCodes(
  codes: string[],
): IndustryStarterProduct[] {
  const set = new Set(codes.map((c) => c.trim().toUpperCase()));
  return DEFAULT_INDUSTRY_STARTER_PRODUCTS.filter((p) =>
    set.has(p.code.toUpperCase()),
  );
}
