import {
  CORE_CAPABILITIES,
  INVENTORY_CAPABILITIES,
  SALES_CAPABILITIES,
  PURCHASING_CAPABILITIES,
  FINANCE_CAPABILITIES,
  PHARMACY_CAPABILITIES,
  REPORTING_CAPABILITIES,
} from "./catalogue";

export const CAPABILITIES = [
  ...CORE_CAPABILITIES,
  ...INVENTORY_CAPABILITIES,
  ...SALES_CAPABILITIES,
  ...PURCHASING_CAPABILITIES,
  ...FINANCE_CAPABILITIES,
  ...PHARMACY_CAPABILITIES,
  ...REPORTING_CAPABILITIES,

];