export const STOCK_MOVEMENTS = {
  OPENING_STOCK: "OPENING_STOCK",
  PURCHASE: "PURCHASE",
  SALE: "SALE",
  SALE_RETURN: "SALE_RETURN",
  PURCHASE_RETURN: "PURCHASE_RETURN",
  ADJUSTMENT: "ADJUSTMENT",
  TRANSFER_IN: "TRANSFER_IN",
  TRANSFER_OUT: "TRANSFER_OUT",
  DAMAGED: "DAMAGED",
  EXPIRED: "EXPIRED",
} as const;