import type { NavigationItem } from "./navigation.types";

import {
  LayoutDashboard,
  Package,
  Boxes,
  Truck,
  ShoppingCart,
  Receipt,
  Wallet,
  BarChart3,
  Settings,
  GitBranch,
  Warehouse,
  Users,
  ShieldCheck,
  Building2,
  Hash,
  Ruler,
  ClipboardList,
  FolderTree,
  ArrowRightLeft,
  PackageCheck,
  FileText,
  ReceiptText,
  RotateCcw,
  CreditCard,
  Banknote,
  CircleDollarSign,
  UsersRound,
  Wrench,
} from "lucide-react";

export const navigation: NavigationItem[] = [
  {
    label: "Dashboard",
    href: "/dashboard",
    icon: LayoutDashboard,
    // No permission needed - always visible
  },
  {
    label: "Capabilities",
    href: "/settings/capabilities",
    icon: Wrench,
    permission: "business.view",
  },
  {
    label: "Sales",
    icon: ShoppingCart,
    module: "sales", // Module name for grouping
    children: [
      {
        label: "POS",
        href: "/sales/pos",
        icon: ShoppingCart,
        permission: "sales.create",
      },
      {
        label: "Quotations",
        href: "/sales/quotations",
        icon: FileText,
        permission: "sales.view",
      },
      {
        label: "Sales Orders",
        href: "/sales/orders",
        icon: ReceiptText,
        permission: "sales.view",
      },
      {
        label: "Invoices",
        href: "/sales/invoices",
        icon: Receipt,
        permission: "sales.view",
      },
      {
        label: "Returns",
        href: "/sales/returns",
        icon: RotateCcw,
        permission: "sales.void",
      },
    ],
  },
  {
   label: "Inventory",
  icon: Package,
  module: "inventory",
  href: "/inventory",
  children: [
  
    {
      label: "Products",
      href: "/inventory/products",
      icon: Package,
      permission: "products.view",
    },
    {
      label: "Categories",
      href: "/inventory/categories",
      icon: FolderTree,
      permission: "categories.view",
    },
    {
      label: "Manufacturers",
      href: "/inventory/manufacturers",
      icon: Building2,
      permission: "products.view",
    },
    {
      label: "Pharmacy catalogues",
      href: "/inventory/pharmacy-catalogues",
      icon: ClipboardList,
      permission: "products.view",
    },
    {
      label: "Stock",
      href: "/inventory/stock",
      icon: Boxes,
      permission: "stock_movements.view",
    },
    {
      label: "Stock Movements",
      href: "/inventory/stock-movements",
      icon: ArrowRightLeft,
      permission: "stock_movements.view",
    },
    {
      label: "Adjustments",
      href: "/inventory/adjustments",
      icon: PackageCheck,
      permission: "stock_adjustments.view",
    },
    {
      label: "Transfers",
      href: "/inventory/transfers",
      icon: ArrowRightLeft,
      permission: "stock_transfers.view",
    },
    {
      label: "Product Batches",
      href: "/inventory/batches",
      icon: ClipboardList,
      permission: "product_batches.view",
    },
    {
      label: "Price Lists",
      href: "/inventory/price-lists",
      icon: FileText,
      permission: "price_lists.view",
    },
    {
      label: "Product Prices",
      href: "/inventory/product-prices",
      icon: CircleDollarSign,
      permission: "product_prices.view",
    },
  ],
},
  {
    label: "Purchasing",
    icon: ClipboardList,
    module: "purchasing",
    children: [
      {
        label: "Suppliers",
        href: "/inventory/suppliers",
        icon: Truck,
        permission: "suppliers.view",
      },
      {
        label: "Purchase Orders",
        href: "/purchases/orders",
        icon: ClipboardList,
        permission: "purchase_orders.view",
      },
      {
        label: "Goods Received",
        href: "/purchases/receiving",
        icon: PackageCheck,
        permission: "goods_receipts.view",
      },
      {
        label: "Supplier Returns",
        href: "/purchases/returns",
        icon: PackageCheck,
        permission: "goods_receipts.view",
      },
    ],
  },
  {
    label: "CRM",
    icon: UsersRound,
    module: "crm",
    children: [
      {
        label: "Customers",
        href: "/customers",
        icon: UsersRound,
        permission: "customers.view",
      },
    ],
  },
  {
    label: "Finance",
    icon: Wallet,
    module: "finance",
    children: [
      {
        label: "Payments",
        href: "/finance/payments",
        icon: CreditCard,
        permission: "payments.view",
      },
      {
        label: "Expenses",
        href: "/finance/expenses",
        icon: Banknote,
        permission: "expenses.view",
      },
      {
        label: "Other income",
        href: "/finance/incomes",
        icon: Banknote,
        permission: "accounts.view",
      },
      {
        label: "Cash & bank",
        href: "/finance/cash-accounts",
        icon: Wallet,
        permission: "accounts.view",
      },
      {
        label: "Daily reconciliation",
        href: "/finance/reconciliation",
        icon: ClipboardList,
        permission: "accounts.view",
      },
      {
        label: "Tax rates",
        href: "/finance/tax-rates",
        icon: CircleDollarSign,
        permission: "accounts.view",
      },
      {
        label: "Chart of accounts",
        href: "/finance/accounts",
        icon: CircleDollarSign,
        permission: "accounts.view",
      },
      {
        label: "Journals",
        href: "/finance/journals",
        icon: FileText,
        permission: "accounts.view",
      },
      {
        label: "AP aging",
        href: "/finance/ap-aging",
        icon: ReceiptText,
        permission: "accounts.view",
      },
    ],
  },
  {
    label: "Reports",
    icon: BarChart3,
    module: "reports",
    children: [
      {
        label: "Overview",
        href: "/reports",
        icon: BarChart3,
        permission: "reports.view",
      },
      {
        label: "Sales Reports",
        href: "/reports/sales",
        icon: BarChart3,
        permission: "reports.view",
      },
      {
        label: "Inventory Reports",
        href: "/reports/inventory",
        icon: Package,
        permission: "reports.view",
      },
      {
        label: "Financial Reports",
        href: "/reports/finance",
        icon: Wallet,
        permission: "reports.view",
      },
      {
        label: "Audit trail",
        href: "/reports/audit",
        icon: ClipboardList,
        permission: "reports.view",
      },
    ],
  },
  {
    label: "Operations",
    icon: Settings,
    module: "operations",
    children: [
      {
        label: "Branches",
        href: "/settings/branches",
        icon: GitBranch,
        permission: "branches.view",
      },
      {
        label: "Warehouses",
        href: "/settings/warehouses",
        icon: Warehouse,
        permission: "warehouses.view",
      },
      {
        label: "Users",
        href: "/settings/users",
        icon: Users,
        permission: "users.view",
      },
    ],
  },
  {
    label: "Settings",
    icon: Settings,
    module: "settings",
    children: [
      {
        label: "Overview",
        href: "/settings",
        icon: Settings,
        permission: "business.view",
      },
      {
        label: "Business Profile",
        href: "/settings/business",
        icon: Building2,
        permission: "business.view",
      },
      {
        label: "Capabilities",
        href: "/settings/capabilities",
        icon: Wrench,
        permission: "business.view",
      },
      {
        label: "Roles & Permissions",
        href: "/settings/roles",
        icon: ShieldCheck,
        permission: "roles.view",
      },
      {
        label: "Units",
        href: "/settings/units",
        icon: Ruler,
        permission: "units.view",
      },
      {
        label: "Audit log",
        href: "/settings/audit-log",
        icon: ClipboardList,
        permission: "accounts.view",
      },
      {
        label: "Numbering",
        href: "/settings/numbering",
        icon: Hash,
        permission: "numbering_sequences.view",
      },
      {
        label: "Payment methods",
        href: "/settings/payment-methods",
        icon: CreditCard,
        permission: "business.view",
      },
      {
        label: "Currencies",
        href: "/settings/currencies",
        icon: CircleDollarSign,
        permission: "business.view",
      },
    ],
  },
];
