import type { CapabilityDefinition } from "../../../types";

export const INDUSTRY_PACK_CAPABILITIES: CapabilityDefinition[] = [
  {
    id: "industry.hospitality",
    code: "HOSPITALITY",
    name: "Hospitality / F&B",
    description:
      "Tables, kitchen tickets, recipe-style stock use for restaurants, cafes, bars and hotels.",
    module: "SALES",
    group: "SALES",
    category: "SALES",
    status: "ACTIVE",
    industries: ["RESTAURANT", "CAFE", "HOTEL", "BAR", "BAKERY"],
    defaultEnabled: false,
    dependencies: ["sales.pos"],
    conflicts: [],
    schema: [],
    services: ["hospitality"],
    ui: ["kitchen", "tables"],
    workflows: [],
    validators: [],
    permissions: [],
    featureFlags: ["hospitality", "restaurant"],
  },
  {
    id: "industry.automotive",
    code: "AUTOMOTIVE",
    name: "Automotive / spare parts",
    description:
      "Vehicle / VIN references, fitment notes, and serialised parts for garages and spares shops.",
    module: "INVENTORY",
    group: "PRODUCTS",
    category: "PRODUCT",
    status: "ACTIVE",
    industries: ["GARAGE", "SPARE_PARTS", "TYRE_CENTER"],
    defaultEnabled: false,
    dependencies: ["inventory.product-types"],
    conflicts: [],
    schema: [],
    services: ["automotive"],
    ui: ["vehicle-ref"],
    workflows: [],
    validators: [],
    permissions: [],
    featureFlags: ["auto", "spares"],
  },
  {
    id: "industry.apparel",
    code: "APPAREL",
    name: "Apparel variants",
    description:
      "Size, colour and style variants for clothing, boutique and shoe retail.",
    module: "INVENTORY",
    group: "PRODUCTS",
    category: "PRODUCT",
    status: "ACTIVE",
    industries: ["BOUTIQUE", "CLOTHING", "SHOES"],
    defaultEnabled: false,
    dependencies: ["inventory.product-variants"],
    conflicts: [],
    schema: [],
    services: ["apparel"],
    ui: ["variants"],
    workflows: [],
    validators: [],
    permissions: [],
    featureFlags: ["fashion"],
  },
  {
    id: "industry.agrovet",
    code: "AGROVET",
    name: "Agrovet / farm supplies",
    description:
      "Batch and expiry for agrochemicals and animal health products.",
    module: "INVENTORY",
    group: "INVENTORY",
    category: "STOCK",
    status: "ACTIVE",
    industries: ["AGROVET", "FARM_SUPPLIES"],
    defaultEnabled: false,
    dependencies: ["inventory.batch-control", "inventory.expiry-control"],
    conflicts: [],
    schema: [],
    services: ["agrovet"],
    ui: [],
    workflows: [],
    validators: [],
    permissions: [],
    featureFlags: ["agriculture"],
  },
  {
    id: "industry.manufacturing-light",
    code: "MFG_LIGHT",
    name: "Light manufacturing",
    description:
      "Raw material and finished-product types for small manufacturers and bakeries.",
    module: "INVENTORY",
    group: "PRODUCTS",
    category: "PRODUCT",
    status: "ACTIVE",
    industries: ["MANUFACTURER", "BAKERY"],
    defaultEnabled: false,
    dependencies: ["inventory.product-types"],
    conflicts: [],
    schema: [],
    services: ["manufacturing"],
    ui: [],
    workflows: [],
    validators: [],
    permissions: [],
    featureFlags: ["manufacturing"],
  },
  {
    id: "industry.services",
    code: "SERVICES",
    name: "Service products",
    description:
      "Non-stock services (labour, consultancy, repairs) sellable on POS and invoices.",
    module: "SALES",
    group: "SALES",
    category: "SALES",
    status: "ACTIVE",
    industries: [],
    defaultEnabled: true,
    dependencies: ["inventory.product-types"],
    conflicts: [],
    schema: [],
    services: ["services"],
    ui: [],
    workflows: [],
    validators: [],
    permissions: [],
    featureFlags: ["services"],
  },
  {
    id: "industry.optical",
    code: "OPTICAL",
    name: "Optical retail",
    description: "Frames, lenses and prescription-related product attributes.",
    module: "INVENTORY",
    group: "PRODUCTS",
    category: "PRODUCT",
    status: "ACTIVE",
    industries: ["OPTICAL"],
    defaultEnabled: false,
    dependencies: ["inventory.product-types"],
    conflicts: [],
    schema: [],
    services: [],
    ui: [],
    workflows: [],
    validators: [],
    permissions: [],
    featureFlags: ["optical"],
  },
  {
    id: "inventory.multi-unit",
    code: "MULTI_UNIT",
    name: "Multi-unit packaging",
    description:
      "Buy in cartons/boxes and sell in pieces/strips with conversion factors.",
    module: "INVENTORY",
    group: "INVENTORY",
    category: "STOCK",
    status: "ACTIVE",
    industries: [],
    defaultEnabled: true,
    dependencies: ["inventory.product-types"],
    conflicts: [],
    schema: ["product_units"],
    services: ["unit-conversion"],
    ui: ["product-packaging"],
    workflows: [],
    validators: [],
    permissions: [],
    featureFlags: ["uom", "packaging"],
  },
];
