/**
 * Default permissions for system roles.
 *
 * Patterns are expanded against the canonical permission registry only.
 * Keep these in canonical plural/resource namespaces.
 */
export const SYSTEM_ROLE_PERMISSIONS = {
  SUPER_ADMIN: ["*"],

  BUSINESS_OWNER: [
    "dashboard.*",
    "business.*",
    "branches.*",
    "warehouses.*",
    "business_settings.*",
    "fiscal_years.*",
    "numbering_sequences.*",
    "users.*",
    "roles.*",
    "permissions.*",
    "units.*",
    "categories.*",
    "products.*",
    "price_lists.*",
    "product_prices.*",
    "product_batches.*",
    "stock_movements.*",
    "stock_adjustments.*",
    "stock_transfers.*",
    "customers.*",
    "suppliers.*",
    "purchase_orders.*",
    "goods_receipts.*",
    "supplier_returns.*",
    "sales.*",
    "quotations.*",
    "deliveries.*",
    "discounts.*",
    "promotions.*",
    "loyalty.*",
    "finance.*",
    "accounts.*",
    "payments.*",
    "expenses.*",
    "income.*",
    "journals.*",
    "taxes.*",
    "fiscal_periods.*",
    "reconciliations.*",
    "reports.*",
    "analytics.*",
    "forecasts.*",
    "kpis.*",
    "metrics.*",
    "audit.*",
    "notifications.*",
    "integrations.*",
  ],

  ADMINISTRATOR: [
    "dashboard.*",
    "business.*",
    "branches.*",
    "warehouses.*",
    "business_settings.*",
    "fiscal_years.*",
    "numbering_sequences.*",
    "users.*",
    "roles.*",
    "permissions.*",
    "units.*",
    "categories.*",
    "products.*",
    "price_lists.*",
    "product_prices.*",
    "product_batches.*",
    "stock_movements.*",
    "stock_adjustments.*",
    "stock_transfers.*",
    "customers.*",
    "suppliers.*",
    "purchase_orders.*",
    "goods_receipts.*",
    "supplier_returns.*",
    "sales.*",
    "quotations.*",
    "deliveries.*",
    "discounts.*",
    "promotions.*",
    "loyalty.*",
    "finance.*",
    "accounts.*",
    "payments.*",
    "expenses.*",
    "income.*",
    "journals.*",
    "taxes.*",
    "fiscal_periods.*",
    "reconciliations.*",
    "reports.*",
    "analytics.*",
    "forecasts.*",
    "kpis.*",
    "metrics.*",
    "audit.*",
    "notifications.*",
    "integrations.*",
  ],

  MANAGER: [
    "dashboard.view",
    "branches.view",
    "branches.export",
    "warehouses.*",
    "units.*",
    "categories.*",
    "products.*",
    "price_lists.*",
    "product_prices.*",
    "product_batches.*",
    "stock_movements.*",
    "stock_adjustments.*",
    "stock_transfers.*",
    "customers.*",
    "suppliers.*",
    "purchase_orders.*",
    "goods_receipts.*",
    "supplier_returns.*",
    "sales.*",
    "quotations.*",
    "deliveries.*",
    "discounts.*",
    "promotions.*",
    "loyalty.*",
    "reports.*",
    "analytics.*",
    "forecasts.*",
    "kpis.*",
    "metrics.*",
  ],

  ACCOUNTANT: [
    "dashboard.view",
    "finance.*",
    "accounts.*",
    "payments.*",
    "expenses.*",
    "income.*",
    "journals.*",
    "taxes.*",
    "fiscal_periods.*",
    "reconciliations.*",
    "reports.*",
    "analytics.*",
  ],

  PURCHASING_OFFICER: [
    "dashboard.view",
    "suppliers.*",
    "purchase_orders.*",
    "goods_receipts.*",
    "supplier_returns.*",
    "products.view",
    "product_batches.view",
    "warehouses.view",
    "stock_movements.view",
    "reports.print",
    "reports.export",
  ],

  STORE_KEEPER: [
    "dashboard.view",
    "warehouses.*",
    "units.*",
    "categories.*",
    "products.view",
    "products.create",
    "products.update",
    "products.import",
    "products.export",
    "product_prices.view",
    "product_batches.*",
    "stock_movements.*",
    "stock_adjustments.*",
    "stock_transfers.*",
    "reports.print",
    "reports.export",
  ],

  SALES_PERSON: [
    "dashboard.view",
    "products.view",
    "product_prices.view",
    "customers.*",
    "sales.*",
    "sales.payments.view",
    "sales.payments.receive",
    "sales.returns.*",
    "quotations.*",
    "sales.orders.*",
    "deliveries.*",
    "promotions.apply",
    "discounts.create",
    "reports.print",
  ],

  CASHIER: [
    "dashboard.view",
    "products.view",
    "product_prices.view",
    "product_batches.view",
    "customers.view",
    "customers.create",
    "customers.update",
    "sales.view",
    "sales.create",
    "sales.complete",
    "sales.print",
    "sales.payments.view",
    "sales.payments.receive",
    "sales.returns.create",
    "sales.returns.refund",
    "sales.returns.exchange",
    "promotions.apply",
    "discounts.apply",
    "loyalty.earn",
    "loyalty.redeem",
    "warehouses.view",
    "stock_movements.view",
  ],

  PHARMACIST: [
    "dashboard.view",
    "products.view",
    "products.create",
    "products.update",
    "product_prices.view",
    "product_batches.*",
    "customers.*",
    "sales.*",
    "loyalty.*",
    "warehouses.view",
    "stock_movements.view",
    "reports.view",
    "reports.print",
  ],

  DOCTOR: [
    "dashboard.view",
    "customers.view",
    "customers.create",
    "customers.update",
    "products.view",
    "sales.view",
  ],

  NURSE: [
    "dashboard.view",
    "customers.view",
    "customers.update",
    "products.view",
  ],

  RECEPTIONIST: [
    "dashboard.view",
    "customers.*",
    "sales.view",
    "sales.create",
    "quotations.*",
    "loyalty.earn",
  ],
} as const;
